### ISSUE TITLE
No rerendering after redirect

### ISSUE THREAD

**Issue by wookieb** [typehero/type-route#41] opened 2020-07-13 18:17 UTC
Hello. Congratulations for this library. Great API!

I've tried example with redirect.
https://codesandbox.io/s/determined-payne-o00k9?file=/src/index.tsx

While redirect happens from URL
https://o00k9.csb.app/old?ageInYears=10

the page does not rerender with new route.

**Comment by bradenhs** [comment] 2020-07-13 19:56
Yikes! That is an issue - thanks for posting this. Are you able to reproduce locally? I'm wondering if this issue is specific to codesandbox. I wasn't able to reproduce locally. There've been a couple other weird things I've noticed with codesandbox.

**Comment by wookieb** [comment] 2020-07-13 19:57
Yes I was able to reproduce it locally. Exactly the same issue. Do you need an example repo or codesandbox will be enough?

**Comment by bradenhs** [comment] 2020-07-13 19:59
Just in case there are a couple issues layered on top of each other here an example repo would be great! Thanks!

**Comment by wookieb** [comment] 2020-07-13 20:19
Here you go:

https://github.com/wookieb/type-route-issue-41

`npm start`
Open the page. You'll notice message "Redirecting...", url will be changed but no rerender with new route.

**Comment by bradenhs** [comment] 2020-07-13 21:21
The issue was the navigation listener wasn't attached when the redirect happened. This is because React runs the `useEffect` hook in children before parents and originally the navigation listener was being added via `useEffect` in the `RouteProvider` component. I changed the approach taken and resolve the issue. Thanks for reporting this bug @wookieb! A fix has been released in `v0.5.2` (https://github.com/typehero/type-route/releases/tag/0.5.2).

**Closed by bradenhs** 2020-07-13 21:21 UTC
